IF (MINGW)
    message(STATUS "Uninstalling in MINGW")
    exec_program(${CMAKE_COMMAND} ARGS "-E remove_directory ${PROJECT_SOURCE_DIR}/dist/")
ELSE()
    message(STATUS "Uninstalling in Linux")
    exec_program(${CMAKE_COMMAND} ARGS "-E remove ${CMAKE_INSTALL_PREFIX}/bin/kaddressbook2*")
    exec_program(${CMAKE_COMMAND} ARGS "-E remove_directory ${CMAKE_INSTALL_PREFIX}/include/kdepim2google")
    exec_program(${CMAKE_COMMAND} ARGS "-E remove ${CMAKE_INSTALL_PREFIX}/lib/libkdepim2google.so*")
    exec_program(${CMAKE_COMMAND} ARGS "-E remove_directory ${CMAKE_INSTALL_PREFIX}/share/kdepim2google")
ENDIF (MINGW)
